language: python
python:
  - "2.7"
install:
  - pip install pylint
  - pip install pep8
  - pip install coveralls
  - pip install -e . --use-mirrors
script:
  - pep8 --ignore=E501 *.py gstack
  - pylint --rcfile=pylint.rc *.py gstack
  - nosetests --with-coverage --cover-erase --cover-package=gstack
after_success:
  - coveralls
